// Generated by setup-assets.js
export const images = {
  logo: '/assets/images/logo.svg',
  hero: {
    handWave: '/assets/images/hand-wave.svg',
    heroImage: '/assets/images/hero-image.jpg',
    textRounded: '/assets/images/hero-text-rounded.png',
    arrowDown: '/assets/images/arrow-down.svg',
    titleDecoration: '/assets/images/title-decoration.svg',
  },
  social: {
    linkedin: '/assets/images/social/linkedin.svg',
    instagram: '/assets/images/social/instagram.svg',
    facebook: '/assets/images/social/facebook.svg',
    twitter: '/assets/images/social/twitter.svg',
  }
};
